SELECT
    e.EMPLOYEE_ID                       AS ID_FUNCIONARIO,
    e.FIRST_NAME || ' ' || e.LAST_NAME  AS FUNCIONARIO,
    d.DEPARTMENT_NAME                   AS DEPARTAMENTO,
    j.JOB_TITLE                         AS CARGO,
    e.SALARY                            AS SALARIO,
    j.MIN_SALARY                        AS PISO_CARGO,
    j.MAX_SALARY                        AS TETO_CARGO,
    e.COMMISSION_PCT                    AS PCT_COMISSAO,
    TO_CHAR(e.HIRE_DATE, 'YYYY-MM-DD')  AS DATA_ADMISSAO,
    m.FIRST_NAME || ' ' || m.LAST_NAME  AS GESTOR_DIRETO
FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.JOBS        j ON e.JOB_ID        = j.JOB_ID
LEFT JOIN HR.EMPLOYEES   m ON e.MANAGER_ID    = m.EMPLOYEE_ID
WHERE e.SALARY IS NOT NULL
ORDER BY d.DEPARTMENT_NAME, e.SALARY DESC;
