SELECT
    e.EMPLOYEE_ID                       AS ID_FUNCIONARIO,
    e.FIRST_NAME || ' ' || e.LAST_NAME  AS FUNCIONARIO,
    d.DEPARTMENT_NAME                   AS DEPARTAMENTO,
    l.CITY                              AS CIDADE,
    l.STATE_PROVINCE                    AS ESTADO_PROVINCIA,
    c.COUNTRY_NAME                      AS PAIS,
    r.REGION_NAME                       AS REGIAO,
    e.SALARY                            AS SALARIO
FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS   l ON d.LOCATION_ID   = l.LOCATION_ID
LEFT JOIN HR.COUNTRIES   c ON l.COUNTRY_ID    = c.COUNTRY_ID
LEFT JOIN HR.REGIONS     r ON c.REGION_ID     = r.REGION_ID
WHERE e.SALARY IS NOT NULL
ORDER BY r.REGION_NAME, c.COUNTRY_NAME, e.SALARY DESC;
